routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/schedule', function () {
    return view('pages/schedule');
});

Route::group(['prefix' => 'schedule'], function() {
    Route::get('/', 'ScheduleController@index');
    Route::get('/show/{id}', 'ScheduleController@show');
    Route::get('/add', 'ScheduleController@create');
    Route::post('/add', 'ScheduleController@store');
    Route::get('/edit/{id}', 'ScheduleController@edit');
    Route::post('/update', 'ScheduleController@update');
    Route::get('/delete/{key}', 'ScheduleController@destroy');
});

Route::group(['prefix' => 'join'], function() {
    Route::get('/', 'JoinScheduleController@index');
    Route::post('/add', 'JoinScheduleController@store');
    Route::get('/delete/{key}', 'JoinScheduleController@destroy');
});

Route::group(['prefix' => 'myjoin'], function() {
    Route::get('/', 'JoinScheduleController@show');
});

Route::resource('venue', 'VenueController');

Route::resource('arena', 'ArenaController');

Auth::routes();

Route::get('/admin', 'AdminController@index');
Route::get('/user', 'UserController@index');

app/Venue.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Venue extends Model
{
    protected $fillable = ['venue_type'];
    protected $primaryKey = 'venue_id';
}

app/Http/Controllers/VenueController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Venue;

class VenueController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['menu'] = 2;
        $data['title'] = "Tipe Venue";
        $data['venue'] = Venue::all();
        $data['no'] = 1;
        return view('venue.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['menu'] = 2;
        $data['title'] = "Tambahkan Tipe Venue";
        return view('venue.create', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validate = $request->validate([
            'venue_type' => 'required'
        ]);

        $insert = venue::create($request->toArray());
        if($insert == true ){
            $request->session()->flash('success', 'Add venue type success!');
            return redirect()->route('venue.index');
        } else {
            $request->session()->flash('danger', 'Add venue type failed!');
            return redirect()->route('venue.index');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['menu'] = 2;
        $data['title'] = "Edit Tipe Venue";
        $data['venue'] = Venue::find($id);
        return view('venue.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validate = $request->validate([
            'venue_type' => 'required|max:30',
        ]);

        $update = Venue::find($id)->update($request->toArray());
        if($update) {
            $request->session()->flash('success', 'Add venue type success!');
            return redirect()->route('venue.index');
        } else {
            $request->session()->flash('danger', 'Add venue type failed!');
            return redirect()->route('venue.index');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $del = Venue::destroy($id);
        return redirect()->route('venue.index');
    }
}

resources/views/venue/create.blade.php
@extends('layouts.app')

@section('content')

<section class="content row justify-content-center">

    @if ($errors->any())

        @foreach ($errors->all() as $error)
            <p class="alert alert-danger">{{ $error }}</p>
        @endforeach

    @endif

    <div class="card card-secondary card-outline col-md-6">
        <div class="card-header">
            <h3 class="card-title">Form {{$title}} </h3>
        </div>
        <div class="card-body">
            <form action="{{ route('venue.store') }}" method="POST">
                {{ csrf_field() }}
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <p>Venue Type</p>
                            <input type="text" class="form-control" required name="venue_type" value="{{ old('venue_type') }}" >
                        </div>

                    </div>

                </div>
                <input type="submit" class="btn btn-primary float-right" value="Add New Venue">
            </form>
        </div>
    </div>
</section>

@endsection

resources/views/venue/edit.blade.php
@extends('layouts.app')

@section('content')

<section class="content row justify-content-center">
    @if ($errors->any())
        @foreach ($errors->all() as $error)
            <p class="alert alert-danger">{{ $error }}</p>
        @endforeach
    @endif

    <div class="card card-secondary card-outline col-md-6">
        <div class="card-header">
            <h3 class="card-title">Form {{$title}} </h3>
        </div>
        <div class="card-body">
            <form action="{{ route('venue.update', ['arena_id' => $venue->venue_id]) }}" method="POST">
                {{ csrf_field() }}
                {{ method_field('PUT') }}
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <p>Venue type</p>
                            <input type="text" class="form-control" required name="venue_type" value="{{ $venue->venue_type}}" >
                        </div>
                    </div>
                </div>
                <input type="submit" class="btn btn-primary float-right" value="Update Venue">
            </form>
        </div>
    </div>
</section>

@endsection

resources/views/venue/index.blade.php
@extends('layouts.app')

@section('content')


<section class="content row justify-content-center">
    <div class="card card-secondary card-outline col-md-8">
        <div class="card-header">
            @include('layouts.navbar')
            @include('layouts.navbaradmin')
        </div>
        <div class="card-body">
            <h3 class="card-title">
                <a href="{{ route('venue.create') }}" class="btn btn-primary">
                    <i class="fas fa-basketball-ball"></i>
                    Add New
                </a>
            </h3>
            <table class="table table-sm" id="myTable">
                <thead>
                    <tr>
                        <th>No</th>
                        <th>Tipe Venue</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($venue as $row)
                    <tr>
                        <td>{{ $no++}}</td>
                        <td>{{ $row['venue_type'] }}</td>
                        <td>
                            <a href="{{ route('venue.edit',  ['venue_id' => $row['venue_id']]) }}" class="btn btn-success btn-circle btn-sm">
                                <i class="fa fa-cog"></i>
                            </a>
                            <a data-id="{{$row->venue_id}}" class="btn btn-danger btn-circle btn-sm">
                                <i class="fa fa-trash" aria-hidden="true" style="color:white"></i>
                            </a>
                        </td>
                    </tr>
                    @endforeach
                </tbody>

            </table>
        </div>
    </div>
</section>

@endsection


@push('scripts')
<script>
    $(".delete-btn").click(function(){
        alert('tes')
        let id = $(this).attr('data-id');
        if(confirm("Apa anda yakin akan menghapus? ")) {
            $.ajax({
                url : "{{url('/')}}/venue/"+id,
                method : "POST",
                data : {
                    _token : "{{csrf_token()}}",
                    _method : "DELETE",
                }
            })
            .then(function(data){
                location.reload();
            });
        }
    })
</script>
@endpush