routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/schedule', function () {
    return view('pages/schedule');
});

Route::group(['prefix' => 'schedule'], function() {
    Route::get('/', 'ScheduleController@index');
    Route::get('/show/{id}', 'ScheduleController@show');
    Route::get('/add', 'ScheduleController@create');
    Route::post('/add', 'ScheduleController@store');
    Route::get('/edit/{id}', 'ScheduleController@edit');
    Route::post('/update', 'ScheduleController@update');
    Route::get('/delete/{key}', 'ScheduleController@destroy');
});

Route::group(['prefix' => 'join'], function() {
    Route::get('/', 'JoinScheduleController@index');
    Route::post('/add', 'JoinScheduleController@store');
    Route::get('/delete/{key}', 'JoinScheduleController@destroy');
});

Route::group(['prefix' => 'myjoin'], function() {
    Route::get('/', 'JoinScheduleController@show');
});

Route::resource('venue', 'VenueController');

Route::resource('arena', 'ArenaController');

Auth::routes();

Route::get('/admin', 'AdminController@index');
Route::get('/user', 'UserController@index');

app/Arena.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Arena extends Model
{
    protected $fillable = ['arena_name', 'location', 'fasilities', 'price', 'type', 'venue_id', 'available'];
    protected $primaryKey = 'arena_id';
    use SoftDeletes;
    protected $dates = ['delete_at'];
}

app/Http/Controllers/ArenaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Arena;
use App\Venue;
use Illuminate\Support\Facades\DB;

class ArenaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['title'] = "Arenas";
        $data['menu'] = 1;
        $arenas = DB::table('arenas')
                        ->join('venues', 'arenas.venue_id', '=', 'venues.venue_id')
                        ->get()->toArray();
        //ngereturn array dari query builder laravel
        $data['arena'] = json_decode(json_encode($arenas), true);
        $data['no'] = 1;
        return view('arena.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['title'] = "Add New Arenas";
        $data['menu'] = 1;
        $data['venues'] = Venue::all();

        return view('arena.create', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validate = $request->validate([
            'arena_name' => 'required',
            'location' => 'required',
            'fasilities' => 'required',
            'price' => 'required|numeric',
            'type' => 'required',
            'venue_id' => 'required'
        ]);

        $insert = Arena::create($request->toArray());

        return redirect()->route('arena.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data['title'] = "Edit Arenas";
        $data['menu'] = 1;
        $data['arena'] = Arena::find($id);
        $data['venues'] = Venue::all();

        return view('arena.show', $data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['title'] = "Edit Arenas";
        $data['menu'] = 1;
        $data['arena'] = Arena::find($id);
        $data['venues'] = Venue::all();

        return view('arena.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validate = $request->validate([
            'arena_name' => 'required',
            'location' => 'required',
            'fasilities' => 'required',
            'price' => 'required|numeric',
            'type' => 'required',
            'venue_id' => 'required'
        ]);

        $update = Arena::find($id)->update($request->toArray());
        return redirect()->route('arena.index');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {   
        // dd($id); 
       //$data = Arena::where('arena_id',$id)->first();
        //dd($data);
        //$data->delete();
        //return redirect()->route('arena.index')->with('alert-success','Data berhasi dihapus!');
        Arena::destroy($id);
        return redirect()->route('arena.index')->with('alert-success','Data berhasi dihapus!');
    }
}

resources/views/arena/create.blade.php
@extends('layouts.app')

@section('content')

<section class="content col-md-6 row justify-content-center">

    @if ($errors->any())

        @foreach ($errors->all() as $error)
            <p class="alert alert-danger">{{ $error }}</p>
        @endforeach

    @endif

    <div class="card card-secondary card-outline">
        <div class="card-header">
            <h3 class="card-title">Form {{$title}} </h3>
        </div>
        <div class="card-body">
            <form action="{{ route('arena.store') }}" method="POST">
                {{ csrf_field() }}
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <p>Nama Arena</p>
                            <input type="text" class="form-control" required name="arena_name" value="{{ old('arena_name') }}" >
                        </div>
                        <div class="form-group">
                            <p>Lokasi</p>
                            <input type="text" class="form-control" required name="location" value="{{ old('location') }}">
                        </div>
                        <div class="form-group">
                            <p>Fasilitas</p>
                            <input type="text" class="form-control" required name="fasilities" value="{{ old('fasilities') }}">
                        </div>
                    </div>

                    <div class="col-md-6">
                        <div class="form-group">
                            <p>Harga</p>
                            <input type="number" class="form-control" required name="price" value="{{ old('price') }}">
                        </div>
                        <div class="form-group">
                            <p>Tipe</p>
                            <select name="type" class="form-control">
                                <option>- Select one -</option>
                                <option value="indoor" {{ (old("type") == "indoor" ? "selected":"") }} >Indoor</option>
                                <option value="outdoor" {{ (old("type") == "outdoor" ? "selected":"") }} >Outdoor</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <p>Venue</p>

                            <select name="venue_id" class="form-control">
                                <option value=''>- Pilih Satu -</option>
                                @foreach($venues as $list)
                                    <option value="{{ $list['venue_id'] }}"> {{$list['venue_type']}} </option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                </div>
                <input type="submit">
            </form>
        </div>
    </div>
</section>

@endsection

resources/views/arena/edit.blade.php
@extends('layouts.app')

@section('content')

<section class="content col-md-6 row justify-content-center">
    @if ($errors->any())
        @foreach ($errors->all() as $error)
            <p class="alert alert-danger">{{ $error }}</p>
        @endforeach
    @endif

    <div class="card card-secondary card-outline">
        <div class="card-header">
            <h3 class="card-title">Form {{$title}} </h3>
        </div>
        <div class="card-body">
            <form action="{{ route('arena.update', ['arena_id' => $arena->arena_id]) }}" method="POST">
                {{ csrf_field() }}
                {{ method_field('PUT') }}
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <p>Nama Arena</p>
                            <input type="text" class="form-control" required name="arena_name" value="{{ $arena->arena_name }}" >
                        </div>
                        <div class="form-group">
                            <p>Lokasi</p>
                            <input type="text" class="form-control" required name="location" value="{{ $arena->location }}">
                        </div>
                        <div class="form-group">
                            <p>Fasilitas</p>
                            <input type="text" class="form-control" required name="fasilities" value="{{ $arena->fasilities }}">
                        </div>
                    </div>

                    <div class="col-md-6">
                        <div class="form-group">
                            <p>Harga</p>
                            <input type="number" class="form-control" required name="price" value="{{ $arena->price }}">
                        </div>
                        <div class="form-group">
                            <p>Tipe</p>
                            <select name="type" class="form-control">
                                <option>- Select one -</option>
                                <option value="indoor" {{ ($arena->type == 'indoor' ? "selected":"") }}>Indoor</option>
                                <option value="outdoor" {{ ($arena->type == 'outdoor' ? "selected":"") }}>Outdoor</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <p>Venue</p>
                            <select name="venue_id" class="form-control">
                                <option value="">- Pilih Satu -</option>
                                @foreach($venues as $venue)
                                    <option value="{{$venue->venue_id}}" {{($arena->venue_id == $venue->venue_id ? 'selected' : '')}} >{{$venue->venue_type}}</option>
                                 @endforeach
                            </select>
                        </div>
                    </div>
                </div>
                <input type="submit">
            </form>
        </div>
    </div>
</section>

@endsection

resources/views/arena/index.blade.php
@extends('layouts.app')

@section('content')

<section class="content row justify-content-center">
    <div class="card card-secondary card-outline col-md-8">
        <div class="card-header">
            @include('layouts.navbar')
            @include('layouts.navbaradmin')
        </div>
        <div class="card-body">
            <a href="{{ route('arena.create') }}" class="btn btn-primary">
                <i class="fas fa-basketball-ball"></i>
                Add New
            </a><hr>
            <table class="table table-sm" id="myTable">
                <thead>
                    <tr>
                        <th>No</th>
                        <th>Nama Arena</th>
                        <th>Lokasi</th>
                        <!-- <th>Fasilitas</th>
                        <th>Harga</th>
                        <th>Tipe</th>
                        <th>Venue</th>-->
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($arena as $row)
                    <tr>
                        <td>{{ $no++}}</td>
                        <td>{{ $row['arena_name'] }}</td>
                        <td>{{ $row['location'] }}</td>
                        <!-- <td>{{ $row['fasilities'] }}</td>
                        <td>{{ number_format($row['price']) }}</td>
                        <td>{{ $row['type'] }}</td>
                        <td>{{ $row['venue_type'] }}</td> -->
                        <td>
                            <a href="{{ route('arena.show',  ['arena_id' => $row['arena_id']]) }}" class="btn btn-sm btn-success btn-circle">
                                <i class="fa fa-eye"></i>
                            </a>
                            <a href="{{ route('arena.edit',  ['arena_id' => $row['arena_id']]) }}" class="btn btn-sm btn-warning btn-circle">
                                <i class="fa fa-edit"></i>
                            </a>
                            <!--<a data-id="{{$row['arena_id']}}" class="btn btn-sm btn-danger delete-btn btn-circle">
                                <i class="fa fa-trash" style="color:white"></i>
                            </a>-->
                            <form style="display: inline;" action="{{ route('arena.destroy', ['arena_id' => $row['arena_id']]) }}" method="post">
                                    {{ csrf_field() }}
                                    {{ method_field('DELETE') }}
                                <button class="btn btn-sm btn-danger delete-btn btn-circle" type="submit" onclick="return confirm('Yakin ingin menghapus data?')">
                                <i class="fa fa-trash" style="color:white"></i>
                            </form>
                            </button>
                        </td>
                    </tr>
                    @endforeach
                </tbody>

            </table>
        </div>
    </div>
</section>


@endsection

resources/views/arena/show.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    Detail of Arena
                </div>

                <div class="card-body">
                {{ method_field('PUT') }}
                        <table class="table">
                            <tr>
                                <td>Nama</td>
                                <td>:</td>
                                <td>{{ $arena->arena_name }}</td>
                            </tr>
                            <tr>
                                <td>Lokasi</td>
                                <td>:</td>
                                <td>{{ $arena->location }}</td>
                            </tr>
                            <tr>
                                <td>Fasilitas</td>
                                <td>:</td>
                                <td>{{ $arena->fasilities }}</td>
                            </tr>
                            <tr>
                                <td>Harga</td>
                                <td>:</td>
                                <td>{{ $arena->price }}</td>
                            </tr>
                            <tr>
                                <td>Type</td>
                                <td>:</td>
                                <td>{{ $arena->type }}</td>
                            </tr>
                            <!-- <tr>
                                <td>Venue</td>
                                <td>:</td>
                                <td>{{ $arena->venue_type }}</td>
                            </tr> -->
                        </table>
                    <hr>
                    <a href="/arena" class="btn btn-primary float-right">Back</a>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection